name: CI
on: [push, pull_request]

jobs:

  windows-clblast:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [Release]
        arch: [x64]
        blas: [ON]
        sdl2: [ON]
        include:
          - arch: x64
            obzip: https://github.com/CNugteren/CLBlast/releases/download/1.6.0/CLBlast-1.6.0-windows-x64.7z
            s2arc: x64
          - sdl2: ON
            s2ver: 2.26.0

    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Fetch SDL2 and set SDL2_DIR
        if: matrix.sdl2 == 'ON'
        run: |
          C:/msys64/usr/bin/wget.exe -qO sdl2.zip https://github.com/libsdl-org/SDL/releases/download/release-${{ matrix.s2ver }}/SDL2-devel-${{ matrix.s2ver }}-VC.zip
          7z x sdl2.zip
          echo "SDL2_DIR=$env:GITHUB_WORKSPACE/SDL2-${{ matrix.s2ver }}/cmake" >> $env:GITHUB_ENV

      - name: Install OpenCL
        run: vcpkg.exe --triplet=${{ matrix.config.arch }}-windows install opencl clblast sdl2

      - name: Configure
        run: >
          cmake -S . -B ./build -A ${{ matrix.arch }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build }}
          #-DWHISPER_SUPPORT_OPENBLAS=${{ matrix.blas }}
          #-DCMAKE_LIBRARY_PATH="$env:blasdir/lib"
          -DWHISPER_EXAMPLES=ON
          -DWHISPER_SUPPORT_SDL2=${{ matrix.sdl2 }}
          -DWHISPER_CLBLAST=ON
          -DOPENCL_ROOT=C:\vcpkg\packages\opencl_x64-windows

      - name: Build
        run: |
          cd ./build
          msbuild ALL_BUILD.vcxproj -t:build -p:configuration=${{ matrix.build }} -p:platform=${{ matrix.arch }}

      - name: Copy libopenblas.dll
        if: matrix.blas == 'ON'
        run: copy "$env:blasdir/bin/libopenblas.dll" build/bin/${{ matrix.build }}

      - name: Copy SDL2.dll
        run: copy "$env:SDL2_DIR/../lib/${{ matrix.s2arc }}/SDL2.dll" build/bin/${{ matrix.build }}

      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: whisper-blas-bin-${{ matrix.arch }}
          #path: build/bin/${{ matrix.build }}
          
  build_windows:
    strategy:
      matrix:
        config: [
          {os: windows-2019, arch: x64},
        ]

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install OpenBLAS
      run: |
        mkdir openblas
        cd openblas
        C:\msys64\usr\bin\wget.exe https://github.com/xianyi/OpenBLAS/releases/download/v0.3.23/OpenBLAS-0.3.23-x64.zip
        7z x OpenBLAS-0.3.23-x64.zip
        pwd
        ls
    - name: Install OpenCL
      run: vcpkg.exe --triplet=${{ matrix.config.arch }}-windows install opencl clblast sdl2

    - name: Run CMake
      run: cmake -S . -B build -DTESTS=ON -DCLIENTS=ON -DSAMPLES=ON -DOPENCL_ROOT=C:\vcpkg\packages\opencl_x64-windows -DCBLAS_ROOT=${{ github.workspace }}\openblas

    - name: Compile the code
      run: cmake --build build
